name: Flight Price ETL Pipeline

on:
  schedule:
    - cron: "30 17 * * *"  # Runs daily at 5:30 PM GMT
  workflow_dispatch:  # Allows manual trigger

jobs:
  flight_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found, skipping..."; fi
          wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar -P $SPARK_HOME/jars
          wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar -P $SPARK_HOME/jars


      - name: Configure AWS Credentials  # <-- ADD THIS STEP
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Fetch Flight Price Data
        run: python scripts/fetch_flight_data.py
        env:
          FLIGHTS_API_URL: ${{ secrets.FLIGHTS_API_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Process Flight Price Data
        run: python scripts/process_flight_data.py
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Store Flight Price Data in RDS
        run: python scripts/store_flight_data.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
